* Phenology Programs and Scripts

This repository is my attempt to organize some programs and scripts
related to phenology, the study of plant evolution through digital
images. Below you'll find the requirements to make this project useful
for you. All code available here is released under the GPLv3. Feel
free to copy, modify and do whatever you want. Contributions are very
welcomed to improve the robustness or anything else you might find
important. In case of problems, [[https://github.com/schnorr/phenology/issues][report here]].

** Requirements

#+begin_src sh :results output :session :exports both
sudo apt-get install cmake libjpeg-dev r-base
#+end_src

** Cloning, compilation and installation

You might want to customize the =CMAKE_INSTALL_PREFIX= variable to your
machine. In the example below, this project will be made available in
the =/tmp/phenology/= directory.

#+begin_src sh :results output :session :exports both
git clone https://github.com/schnorr/phenology.git
cd phenology ; mkdir build ; cd build
cmake -DCMAKE_INSTALL_PREFIX=/tmp/phenology/ .. ; make install
#+end_src

** Image Directory Organization

The digital images have to be in the JPG file format. No other format
is accepted as of now. They should be organized in the following
directory structure: =db/year/year_sequence.jpg=, where =db= is the name
of the database, it can be anything you want (or need); =year= is a
diretory that will hold all that year's images; =year_sequence.jpg= is
the name of the file: the year part should be preferably the same as
the directory name holding the file and the sequence is a integer or
floating-point number that indicates the sequence of images within
that year. Some examples:

1. This first example has four images (we can notice that the image
   003 is missing - that is okay).

   #+BEGIN_EXAMPLE
   db01/2004/2004_001.jpg
   db01/2004/2004_002.jpg
   db01/2004/2004_004.jpg
   db01/2004/2004_005.jpg
   #+END_EXAMPLE



